version: 1.0
app:
  instances: 1
  version: eb1761b2-a991-419e-84a0-f73f745dc5dd
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  mounts:
    - path: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/myconfig.xml
      value: |
        <server>
            <var name="io_openliberty_sample_system_inMaintenance" value="false"/>
        </server>
